### ISSUE TITLE
don't use bower

### ISSUE THREAD

**Issue by akatov** [yapplabs/ember-cli-bourbon#17]
would you consider a pull request which got rid of bower along the lines of ember-cli-moment-shim
(see https://github.com/jasonmit/ember-cli-moment-shim/blob/master/index.js)
The idea is to import the front-end dependency as an npm dependency, then use `require.resolve` to look up the path in ember-cli-build.

**Comment by oliverlangan** [comment]
+1, I think this is a good way to go.

**Comment by oligriffiths** [comment]
@lukemelia thoughts on this?

**Comment by lukemelia** [comment]
Definitely open to this!

**Comment by lukemelia** [comment]
In progress in #18

**Comment by lukemelia** [comment]
Published as `2.0.0-beta.0`. Can I get some volunteers to try it out?

**Comment by oligriffiths** [comment]
@lukemelia looks good. I notice that https://github.com/yapplabs/ember-cli-bourbon/blob/v2.0.0-beta.0/blueprints/ember-cli-bourbon/index.js#L9 is still present, is this just so it still works with people using bower or an omission?

**Comment by lukemelia** [comment]
@oligriffiths thanks for the catch. Addressed in #19
