### ISSUE TITLE
[Deprecated] this.pickFiles is deprecated warning for ember CLI 0.2.3

### ISSUE THREAD

**Issue by amhasler** [yapplabs/ember-cli-bourbon#7]
After install of ember-cli-bourbon addon to ember cli 0.2.3 project, starting the server gives me
[Deprecated] this.pickFiles is deprecated, please use broccoli-funnel directly instead  [addon: ember-cli-bourbon]

**Comment by stefanpenner** [comment]
duplicate of: https://github.com/yapplabs/ember-cli-bourbon/pull/6
