### ISSUE TITLE
Does not work with sass file

### ISSUE THREAD

**Issue by JDillon522** [yapplabs/ember-cli-bourbon#9]
Is there a reason I cannot simply add `@import "bourbon"` to my `app.sass` file? I get the following error:

```
Error: file to import not found or unreadable: bourbon
Current dir: /Users/jdillon/Documents/work/project/tmp/tree_merger-tmp_dest_dir-2WDpffwx.tmp/app/styles/
    at options.error (/Users/jdillon/Documents/work/project/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/lib/index.js:276:32)
```

The project I've hopped on is set on sass. 

Also, what do you mean by:

> If you already have content in your app.scss, you can just choose "n" and add that line to the top of app.scss yourself.

Thanks

**Comment by lukemelia** [comment]
@JDillon522 Hmm, I don't think we've tested with sass. I'm happy to help debug if you want to create a simple example app or a failing test.

**Comment by JDillon522** [comment]
yeah sure, i'll what i can do for ya here in a bit
